title: TinyMCE Paste From Word Plugin
description: TinyMCE 6.x Plugin to add support for pasting from Microsoft Word documents

remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
