name: Publish to NPM

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: |
          VER=`echo "${{ github.ref }}" | sed -e 's/refs\/tags\/v//'`
          sed -i "s/^ *\"version\": \".*\", *$/  \"version\": \"$VER\",/" package.json

      - run: npm ci

      - run: npm run build

      - run: |
          cp types/src/main.d.ts dist/index.d.ts
          cp package.json README.md LICENSE dist/

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "dist"
          access: "public"

      - run: npm run build-lib

      - run: |
          cp types/src/plugin/lib.d.ts lib/index.d.ts
          cp package.json README.md LICENSE lib/

      - run: |
          sed -i 's/@pangaeatech\/tinymce-paste-from-word-plugin/@pangaeatech\/tinymce-paste-from-word-lib/' lib/package.json

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "lib"
          access: "public"
